services:
  - type: web
    name: prime-remote-d
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ALLOWED_TELEGRAM_USER_IDS
        sync: false
      - key: API_KEY
        sync: false
